-- TABLE INFO :
-- SALES – Date, Order_id, Item_id, Customer_id, Quantity, Revenue
-- ITEMS – Item_id, Item_name, price, department
-- CUSTOMERS- customer_id, first_name,last_name,Address


-- Pull total number of orders that were completed on 18th March 2023
-- Assuming Date is in dd/mm/yyyy FORMAT
SELECT COUNT(distinct(Order_id))
FROM SALES
WHERE Date = '18/03/2023';


-- Pull total number of orders that were completed on 18th March 2023 with the first name ‘John’ and last name Doe’
SELECT COUNT(distinct(s.Order_id))
FROM SALES s 
LEFT JOIN CUSTOMERS c
ON s.Customer_id = c.customer_id
AND s.Date = '18/03/2023'
AND c.first_name = 'John'
AND c.last_name = 'Doe';

-- Pull total number of customers that purchased in January 2023 and the average amount spend per customer
SELECT COUNT(DISTINCT s.Customer_id) AS Total_Customers, AVG(total_spent) AS Average_Spend
FROM (
    SELECT Customer_id, SUM(Revenue) AS total_spent
    FROM SALES
    WHERE Date BETWEEN '2023-01-01' AND '2023-01-31'
    GROUP BY Customer_id
) AS customer_spending;


-- Pull the departments that generated less than $600 in 2022
SELECT i.department
FROM SALES s JOIN ITEMS i 
ON s.Item_id = i.Item_id
WHERE s.Date BETWEEN '2022-01-01' AND '2022-12-31'
GROUP BY i.department
HAVING total_revenue < 600;

-- What is the most and least revenue we have generated by an order
SELECT MAX(Revenue) AS Max_Revenue, MIN(Revenue) AS Min_Revenue
FROM SALES;

-- What were the orders that were purchased in our most lucrative order

SELECT s.Order_id,s.Item_id,i.Item_name,s.Quantity,s.Revenue
FROM SALES s JOIN ITEMS i 
ON s.Item_id = i.Item_id
WHERE s.Order_id = (
    SELECT Order_id
    FROM SALES
    GROUP BY Order_id
    ORDER BY SUM(Revenue) DESC
    LIMIT 1
);
